### ISSUE TITLE
7July2016 Checklist - Big Picture

### ISSUE THREAD

**Issue by stephpenn1** [stephpenn1/SeniorThesis#1]
- [x] Download data for density script 
- [x] Identify mode and intermediate water by density based on low salinity minimum 
- [ ] Look into potential vorticity - can we calculate it in SeaWater packages? or use mixed layer depth?
- [x] Make surface and depth plots of salinity and density
- [x] Pick certain coordinates of interest
- [x] Averaging over 10 or 20 year period
- [ ] Dominant modes of variability in Pacific

**Comment by cahartin** [comment]
i found some data that you can download!  You will need another username/password
https://www.earthsystemgrid.org/home.html
search
project - cmip5
model - cesm1-bgc
experiment - rcp85
find file with time_frequency=mon, modeling realm=ocean and oceanBgchem
download options
find rhopoto, thetao, so

**Comment by stephpenn1** [comment]
I finished downloading the rhopoto, I am having trouble opening the file on my computer (and in Matlab), though. I'm looking on google to see if I'm missing something needed for a Mac or in Matlab

**Comment by cahartin** [comment]
This looks like a pretty easy guide that you could start with.

http://www.public.asu.edu/~hhuang38/matlab_netcdf_guide.pdf

I finished downloading the rhopoto, I am having trouble opening the file on my computer (and in Matlab), though. I'm looking on google to see if I'm missing something needed for a Mac or in Matlab

**Comment by cahartin** [comment]
@stephpenn1  I added a few more lines of code to our quick example script to pull out and average over 1 year of the data.  Recall we had to switch from ncdf to ncdf4 package on your end.  I'll make those changes on my side soon.
