### ISSUE TITLE
October Checklist

### ISSUE THREAD

**Issue by stephpenn1** [stephpenn1/SeniorThesis#10]
- [x] generate difference plots (30/50-hist, 80/100-hist, 80/100-30/50) for **main** variables
- [x] generate difference plots (30/50-hist, 80/100-hist, 80/100-30/50) for **other** variables
- [ ] research dominant modes of variability in S. Pacific
- [x] begin writing introduction and methods for report
