### ISSUE TITLE
November Checklist

### ISSUE THREAD

**Issue by stephpenn1** [stephpenn1/SeniorThesis#11]
- [x] analyze difference plots of main variables
- [x] research future research (for next semester) possibilities
- [x] complete slides for presentation containing preliminary research & future research ideas
