### ISSUE TITLE
Spring Semester Checklist

### ISSUE THREAD

**Issue by stephpenn1** [stephpenn1/SeniorThesis#12]
- [x] download variable data (wind stress, heat flux, freshwater flux, evap-precip) 
- [x] plot these variables
- [x] research effects of wind stress, freshwater flux, and evap-precip on density changes **(February)**
- [x] research formation rate calculations **(February)**
- [x] generate plots(?) for variable data to determine primary driver of changes **(by March 16th - before spring break)**
- [x] calculate density by holding temp/sal constant and varying temp/sal
- [x] calculate formation rates **(March/April)**
