### ISSUE TITLE
Week of 18July2016 Checklist

### ISSUE THREAD

**Issue by stephpenn1** [stephpenn1/SeniorThesis#2]
- [x] Read up/play around on GitHub
- [x] switch longitude to -180 to +180
- [x] change density (ex. 1030 to 30) - double check units
- [x] Pull out certain longitudes to make Depth v. Lat plots
- [x] Look into "apply" function 
- [x] Find out how to make pretty plots (key, title, axes)
- [x] Log into AOSC server - see if there is Matlab, R, etc.
- [x] Figure out how to overlay density and salinity (color and contour) on one plot
