### ISSUE TITLE
September Checklist

### ISSUE THREAD

**Issue by stephpenn1** [stephpenn1/SeniorThesis#9]
- [x] define physical parameters of AAIW
- [x] download other variables & average them (O2/O2 min, silica, pH, age @ surface)
- [x] play around with ggplot/ saving plots
- [x] figure out longitude (if statements), switch longitude to -180/+180
- [x] look into 'fgco2' and 'zo2min' variable
- [x] CDO (R?) bash scripts - research bash scripts & how to use them
- [x] code - open entire directory

**Comment by cahartin** [comment]
@stephpenn1  switch the longitudes using the commands in CDO.

**Comment by stephpenn1** [comment]
@cahartin are you talking about the 'selllonlatbox' command? I tried that last Thursday and I think that the command only creates a magnified "box" of the specific lat, lon parameters.  Is this consistent with what you found? Maybe I did something wrong using CDO
